name: Kitchen Garden Blog
description: I'll cook a new one.
url: http://blog.hifumi.info/
markdown: redcarpet
pygments: true
exclude: ['README.md', 'vendor']
sass:
  syntax: scss
  style:  compressed
