name: Kitchen Garden Blog
description: I'll cook a new one.
url: http://blog.hifumi.info/
markdown: redcarpet
pygments: true
exclude: ['README.md', 'vendor', 'Rakefile', 'config.rb']
sass:
  syntax: scss
  style:  compressed
google_analytics:
  account: UA-18235043-7
