name: 'blog: takahiro okumura'
description: i'm an infra engineer.
url: http://blog.hifumi.info
domain: blog.hifumi.info
timezone: Asia/Tokyo
markdown: redcarpet
redcarpet:
  extensions: [
    'tables',
    'no_intra_emphasis',
    'fenced_code_blocks',
    'autolink',
    'space_after_headers',
    'strikethrough',
    'superscript',
    'underline',
    'highlight',
    'smart',
    'footnotes'
  ]
highlighter: pygments
exclude: ['README.md', 'vendor', 'Rakefile', 'config.rb', 'Gemfile', 'Gemfile.lock']
permalink: /:categories/:year/:month/:day/:title/
paginate: 10
paginate_path: "page:num"
sass:
  syntax: scss
  style:  compressed
google_analytics:
  account: UA-18235043-7
og_image: images/title.png
og_image_type: image/png
og_image_width: 256
og_image_height: 256
fb_admins: 32238
