baseurl = 'http://blog.hifumi.info/'
title = "blog: takahiro okumura"
uglyURLs = false
pygmentscodefences = true
pygmentsstyle = "emacs"
rssuri = "feed.xml"

[permalinks]
  post = "/:year/:month/:day/:filename/"
  nginx = "/nginx/:filename/"

[author]
  name = "OKUMURA Takahiro"
  twitter = "@hfm"
  github = "@hfm"

[params]
  description = "I'm a software engineer of web operations."

[outputFormats.RSS]
  baseName = "feed"
